name: blockpulsar-deploy
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configuring Blockpulsar
        env:
          API_KEY: ${{ secrets.BLOCKPULSAR_KEY }}
          API_SECRET: ${{ secrets.BLOCKPULSAR_SECRET }}
        run: |
          git --version
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git config --local --add safe.directory .
          git remote add bp "https://$API_KEY:$API_SECRET@ci.blockpulsar.com/git"
      - name: Push to Blockpulsar Git
        run: git push bp master
